hola

*## Primer paso, traer el archivo con panda

Puedes utilizar este notebook para analizar el dataset propuesto

In [1]:
from configparser import UNNAMED_SECTION

import pandas as pd
from pandas.conftest import axis

df_pais = pd.read_excel("C:/Users/mauri/PycharmProjects/ucu-python-4-data-analysis-project/data/raw/Paises_Censo2023.xlsx")

#print(df.head())
df_pais

    País_Nombre  País_codigo
0    Afganistán            4
1       Albania            8
2      Alemania          276
3       Algeria           12
4       Andorra           20
..          ...          ...
231  Uzbekistán          860
232     Vanuatu          548
233       Yemen          887
234      Zambia          894
235    Zimbabwe          716

[236 rows x 2 columns]

In [2]:
# Obtener las dimensiones
df_pais.shape

(236, 2)

In [3]:
# Obtener información sobre tipos de datos y valores no nulos
df_pais.info()

<class 'pandas.DataFrame'>
RangeIndex: 236 entries, 0 to 235
Data columns (total 2 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   País_Nombre  236 non-null    str
 1   País_codigo  236 non-null    int64
dtypes: int64(1), str(1)
memory usage: 6.7 KB

In [4]:
df_pais.describe().T

             count        mean         std  min     25%    50%     75%    max
País_codigo  236.0  441.254237  252.488725  4.0  229.75  441.0  659.25  894.0

In [5]:
df_pais.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
231    False
232    False
233    False
234    False
235    False
Length: 236, dtype: bool

In [6]:
df_pais[df_pais.duplicated(subset=["País_Nombre"])]

Empty DataFrame
Columns: [País_Nombre, País_codigo]
Index: []

In [7]:
df_pais[df_pais.duplicated(subset=["País_codigo"])]

Empty DataFrame
Columns: [País_Nombre, País_codigo]
Index: []

In [8]:
df_censo = pd.read_csv("C:/Users/mauri/PycharmProjects/ucu-python-4-data-analysis-project/data/raw/hogares_ext_26_02.csv")

#print(df.head())
df_censo

,Unnamed: 0,DIRECCION_ID,DEPARTAMENTO,LOCALIDAD,VIVID,HOGID,REGION_4,AREA,MUNICIPIO_PAIS,TIPO_MUNICIPIO_PAIS,...,HOGCE28,HOGCE11,HOGCE22,HOGCE12_1,HOGCE13,HOGMA01_1,HOGMA01_1_1,HOGMA01_2,HOGMA01_2_1,HOGPR01_CON_RRAA
0,1,1000001,1,20,1,1,1,1,Municipio B,C,...,1,1,1,2,0,2,7777,2,7777,2
1,2,1000002,1,20,1,1,1,1,Municipio B,C,...,1,1,2,2,1,2,7777,2,7777,2
2,3,1000003,1,20,1,1,1,1,Municipio B,C,...,1,1,1,2,1,1,2,1,2,2
3,4,1000004,1,20,1,1,1,1,Municipio B,C,...,1,1,2,2,0,2,7777,2,7777,1
4,5,1000005,1,20,1,1,1,1,Municipio B,C,...,1,1,1,2,1,2,7777,2,7777,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255199,1255200,3274802,3,24,1,1,2,1,Paso Carrasco,C,...,1,1,1,1,2,1,1,2,7777,5
1255200,1255201,3274803,3,24,1,1,2,1,Paso Carrasco,C,...,1,1,2,1,2,1,1,2,7777,4
1255201,1255202,3274804,3,24,1,1,2,1,Paso Carrasco,C,...,1,1,1,2,1,2,7777,2,7777,1
1255202,1255203,3274805,3,24,1,1,2,1,Paso Carrasco,C,...,1,1,1,2,1,1,1,2,7777,3
1255203,1255204,16053338,16,9898,1,1,3,1,NaN,NaN,...,7777,7777,7777,7777,7777,7777,7777,7777,7777,25

In [11]:
df_censo.drop(['Unnamed: 0'], axis=1, inplace=True)
df_censo

,DIRECCION_ID,DEPARTAMENTO,LOCALIDAD,VIVID,HOGID,REGION_4,AREA,MUNICIPIO_PAIS,TIPO_MUNICIPIO_PAIS,VIVVO00,...,HOGCE28,HOGCE11,HOGCE22,HOGCE12_1,HOGCE13,HOGMA01_1,HOGMA01_1_1,HOGMA01_2,HOGMA01_2_1,HOGPR01_CON_RRAA
0,1000001,1,20,1,1,1,1,Municipio B,C,1,...,1,1,1,2,0,2,7777,2,7777,2
1,1000002,1,20,1,1,1,1,Municipio B,C,1,...,1,1,2,2,1,2,7777,2,7777,2
2,1000003,1,20,1,1,1,1,Municipio B,C,1,...,1,1,1,2,1,1,2,1,2,2
3,1000004,1,20,1,1,1,1,Municipio B,C,1,...,1,1,2,2,0,2,7777,2,7777,1
4,1000005,1,20,1,1,1,1,Municipio B,C,1,...,1,1,1,2,1,2,7777,2,7777,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1255199,3274802,3,24,1,1,2,1,Paso Carrasco,C,1,...,1,1,1,1,2,1,1,2,7777,5
1255200,3274803,3,24,1,1,2,1,Paso Carrasco,C,1,...,1,1,2,1,2,1,1,2,7777,4
1255201,3274804,3,24,1,1,2,1,Paso Carrasco,C,1,...,1,1,1,2,1,2,7777,2,7777,1
1255202,3274805,3,24,1,1,2,1,Paso Carrasco,C,1,...,1,1,1,2,1,1,1,2,7777,3
1255203,16053338,16,9898,1,1,3,1,NaN,NaN,2,...,7777,7777,7777,7777,7777,7777,7777,7777,7777,25

In [15]:
df_filtrado = pd.read_csv("C:/Users/mauri/PycharmProjects/ucu-python-4-data-analysis-project/data/raw/personas_ext_26_02.csv", usecols=["PERED03", "PERED03_1", "PERPH02", "PERED04","DEPARTAMENTO"])
df_filtrado

         DEPARTAMENTO  PERPH02  PERED03  PERED03_1  PERED04
0                   1        2     8888       8888     8888
1                   1        1     8888       8888     8888
2                   1        2     8888       8888     8888
3                   1        2     8888       8888     8888
4                   1        2     8888       8888     8888
...               ...      ...      ...        ...      ...
3499446            16        1     8888       7777     7777
3499447            16        1     8888          2     7777
3499448            16        2     8888          2     7777
3499449            16        2     8888          2     7777
3499450            16        1     8888          2     7777

[3499451 rows x 5 columns]

In [33]:
df_per_filtrado = pd.read_csv("C:/Users/mauri/PycharmProjects/ucu-python-4-data-analysis-project/data/raw/personas_ext_26_02.csv", usecols=["PERED03", "PERED03_1", "PERPH02", "PERED04","HOGID","DEPARTAMENTO","DIRECCION_ID", "VIVID"])
df_per_filtrado

,DIRECCION_ID,DEPARTAMENTO,VIVID,HOGID,PERPH02,PERED03,PERED03_1,PERED04
0,1146859.0,1,1.0,1.0,2,8888,8888,8888
1,1146859.0,1,1.0,1.0,1,8888,8888,8888
2,1313925.0,1,1.0,1.0,2,8888,8888,8888
3,1313925.0,1,1.0,1.0,2,8888,8888,8888
4,1313925.0,1,1.0,1.0,2,8888,8888,8888
...,...,...,...,...,...,...,...,...
3499446,16053338.0,16,1.0,1.0,1,8888,7777,7777
3499447,16053338.0,16,1.0,1.0,1,8888,2,7777
3499448,16053338.0,16,1.0,1.0,2,8888,2,7777
3499449,16053338.0,16,1.0,1.0,2,8888,2,7777
3499450,16053338.0,16,1.0,1.0,1,8888,2,7777

In [35]:
df_hog_filtrado = pd.read_csv("C:/Users/mauri/PycharmProjects/ucu-python-4-data-analysis-project/data/raw/hogares_ext_26_02.csv", usecols=["HOGID","DEPARTAMENTO","REGION_4","AREA","MUNICIPIO_PAIS","HOGCE28", "HOGCE11" ,"DIRECCION_ID", "VIVID"])
df_hog_filtrado

,DIRECCION_ID,DEPARTAMENTO,VIVID,HOGID,REGION_4,AREA,MUNICIPIO_PAIS,HOGCE28,HOGCE11
0,1000001,1,1,1,1,1,Municipio B,1,1
1,1000002,1,1,1,1,1,Municipio B,1,1
2,1000003,1,1,1,1,1,Municipio B,1,1
3,1000004,1,1,1,1,1,Municipio B,1,1
4,1000005,1,1,1,1,1,Municipio B,1,1
...,...,...,...,...,...,...,...,...,...
1255199,3274802,3,1,1,2,1,Paso Carrasco,1,1
1255200,3274803,3,1,1,2,1,Paso Carrasco,1,1
1255201,3274804,3,1,1,2,1,Paso Carrasco,1,1
1255202,3274805,3,1,1,2,1,Paso Carrasco,1,1
1255203,16053338,16,1,1,3,1,NaN,7777,7777

# Título

Texto normal

- elemento 1
- elemento 2

In [39]:
##df_final = pd.concat([df_per_filtrado, df_hog_filtrado], ignore_index=True)

df_final =  df_per_filtrado.merge(df_hog_filtrado, on="DIRECCION_ID", how="inner")
df_final

,DIRECCION_ID,DEPARTAMENTO_x,VIVID_x,HOGID_x,PERPH02,PERED03,PERED03_1,PERED04,DEPARTAMENTO_y,VIVID_y,HOGID_y,REGION_4,AREA,MUNICIPIO_PAIS,HOGCE28,HOGCE11
0,1146859.0,1,1.0,1.0,2,8888,8888,8888,1,1,1,1,1,Municipio E,8888,8888
1,1146859.0,1,1.0,1.0,1,8888,8888,8888,1,1,1,1,1,Municipio E,8888,8888
2,1313925.0,1,1.0,1.0,2,8888,8888,8888,1,1,1,1,1,Municipio D,8888,8888
3,1313925.0,1,1.0,1.0,2,8888,8888,8888,1,1,1,1,1,Municipio D,8888,8888
4,1313925.0,1,1.0,1.0,2,8888,8888,8888,1,1,1,1,1,Municipio D,8888,8888
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3217527,16053338.0,16,1.0,1.0,1,8888,7777,7777,16,1,1,3,1,NaN,7777,7777
3217528,16053338.0,16,1.0,1.0,1,8888,2,7777,16,1,1,3,1,NaN,7777,7777
3217529,16053338.0,16,1.0,1.0,2,8888,2,7777,16,1,1,3,1,NaN,7777,7777
3217530,16053338.0,16,1.0,1.0,2,8888,2,7777,16,1,1,3,1,NaN,7777,7777
3217531,16053338.0,16,1.0,1.0,1,8888,2,7777,16,1,1,3,1,NaN,7777,7777